# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papermanager', '0006_paperfiles_paperversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Review Pending'), ('Y', 'Accepted'), ('N', 'Rejected')], max_length=1)),
                ('paperversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papermanager.PaperVersion')),
            ],
        ),
    ]
