# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatus',
            name='paperversion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='papermanager.PaperVersion'),
        ),
    ]
