# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0002_auto_20180106_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatus',
            name='status',
            field=models.CharField(choices=[('W', 'Not yet submitted'), ('P', 'Review Pending'), ('Y', 'Accepted'), ('N', 'Rejected')], default='W', max_length=1),
        ),
    ]
