# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0012_paperfiles_from_reviewer'),
        ('paperreviewer', '0003_auto_20180106_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposedPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', slugger.fields.AutoSlugField(populate_from='pdf_file__name', unique=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papermanager.PaperFiles')),
            ],
        ),
    ]
