# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paperreviewer', '0004_exposedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposedpdf',
            name='randomseed',
            field=models.CharField(default='NA68BXxAvrq506R8SdLa', max_length=20),
        ),
        migrations.AlterField(
            model_name='exposedpdf',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='randomseed', unique=True),
        ),
    ]
