# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaperFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filedata', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('submissionType', models.CharField(choices=[('latex', 'Lamport TeX (LaTeX)'), ('pdf', 'Portable Document Format (PDF)')], max_length=7)),
                ('submissionDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
