# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 11:55
from __future__ import unicode_literals

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0002_paper_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=slugger.fields.AutoSlugField(default=1, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
