# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0003_paper_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperversion',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papermanager.Paper'),
            preserve_default=False,
        ),
    ]
