# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0004_paperversion_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperversion',
            name='slug',
            field=slugger.fields.AutoSlugField(default=1, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperversion',
            name='submissionType',
            field=models.CharField(choices=[('latex', 'Lamport TeX (LaTeX)'), ('pdf', 'Portable Document Format (PDF)')], default='latex', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='paperversion',
            unique_together=set([('name', 'paper')]),
        ),
    ]
