# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0005_auto_20171215_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfiles',
            name='paperversion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='papermanager.PaperVersion'),
            preserve_default=False,
        ),
    ]
