# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papermanager', '0006_paperfiles_paperversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reviewer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reveiwpaper', to=settings.AUTH_USER_MODEL),
        ),
    ]
