# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 13:49
from __future__ import unicode_literals

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0008_auto_20180106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfiles',
            name='slug',
            field=slugger.fields.AutoSlugField(default=1, populate_from='filename'),
            preserve_default=False,
        ),
    ]
