# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0009_paperfiles_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paperfiles',
            unique_together=set([('paperversion', 'slug'), ('filename', 'paperversion')]),
        ),
        migrations.AlterUniqueTogether(
            name='paperversion',
            unique_together=set([('name', 'paper'), ('paper', 'slug')]),
        ),
    ]
