# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0010_auto_20180107_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='public',
        ),
    ]
