# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0011_remove_paper_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfiles',
            name='from_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
