# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseportal', '0002_auto_20180110_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalPaper',
            new_name='PublishedPaper',
        ),
    ]
